#!/usr/bin/env php
<?php
/**
 * Sample Player
 *
 * Provides samples of various simple Move makers
 *
 * @link https://github.com/stjohnjohnson/ScrabblerBot
 * @author St. John Johnson <st.john.johnson@gmail.com>
 */

namespace Scrabbler;

/** Scrabbler Player */
require_once 'src/player.php';

if ($argc < 2) {
  die('Usage: scrabbler.php Wordlist.txt [BotName]' . PHP_EOL);
}

$foo = new Player(array(
    'log' => Player::LOG_INFO,
'lexicon' => $argv[1],
 'method' => isset($argv[2]) ? $argv[2] : 'HighestScore'
));
$foo->execute();
